# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'MyCocoaPod', :path => '/Users/shashankshetty/Downloads/GreetingKMP/shared'
  
  pod 'MyCoreNetwork', :path => '/Users/shashankshetty/Downloads/GreetingKMP/core-network/MyCoreNetwork.podspec'
end
